import React from "react";
import { Providers } from "./providers";
//import { Inter } from 'next/font/google'
import { Links } from './components/links'
import './styles/globals.css'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Wendy Huang | Pianist',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <div className="relative"> 
          <div className="fixed top-100 left-10">
            <Links />
          </div>
      </div>
				<Providers>{children}</Providers>
      </body>
    </html>
  )
}
