import React from "react"
import Headers from './components/Headers'
import Provider from './Provider'
// import ClientLayout from './ClientLayout'
import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Wendy Huang | Pianist',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
      <body>
      <Provider>
       <Headers />
        {children}
        </Provider>
      </body>
    </html>
  )
}
