import React from "react";
//import { Inter } from 'next/font/google'
import { Links } from './components/links'
import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Wendy Huang | Pianist',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Links />
 
        {children}

      </body>
    </html>
  )
}
